### ISSUE TITLE
Sticker images doesn't display

### ISSUE THREAD

**Issue by marciojc** [vsay01/GboardCustomSticker#1]
The installation was successful, but at the gboard the images aren't displayed.
There is any specific step at the firebase?

**Comment by paullegrand** [comment]
I too have been having this issue. I'm not sure what it is, but it appears to be something with how it's accessing the firebase images. I swapped the images out to link to an S3 bucket to see if it would fix it and it did, but the original firebase links don't work. I'm not sure how to make it work with firebase storage as I'm not too familiar with Android programming, so if anyone knows how to fix that, it would be appreciated.

**Comment by vsay01** [comment]
@marciojc and @paullegrand 

Here is firebase official document how to setup: https://firebase.google.com/docs/android/setup

There are three main things you might want to check:
1. After create your firebase project, make sure you download the google-services.json from Firebase project setting and place it in the **app folder** of the project

2. In your firebase project upload test images in **storage**

3. In **StckersDataFactory**, update the link to the uploaded images located in the storage

**Comment by NafeesAsghar** [comment]
"In StckersDataFactory, update the link to the uploaded images located in the storage" where should I update this link and how can you please explain?

Thanks

**Comment by marciojc** [comment]
Hi,
It seems that was a bug from the gboard app. 
Since Dec of 2017 until April 2018 wasn't work. After 10 of April is working again

**Comment by NafeesAsghar** [comment]
Thanks for this information bro I will check it
